// Auto-generated by scripts/generate-inference-config.mjs — do not edit manually.

export interface InferenceConfig {
	thinking_prefix: string;
}

export const INFERENCE_CONFIG: InferenceConfig = {
	"thinking_prefix": "The system prompt contains a CONSTITUTION I must follow. Let me reason through how it applies before responding."
};
